Disaster Alleviation Web/Controllers/AidTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Disaster_Alleviation_Web.Data;
using Disaster_Alleviation_Web.Models;
using Microsoft.AspNetCore.Authorization;

namespace Disaster_Alleviation_Web.Controllers
{
    public class AidTypesController : Controller
    {
        private readonly DisasterReliefContext _context;

        public AidTypesController(DisasterReliefContext context)
        {
            _context = context;
        }

        // GET: AidTypes
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.AidTypes.ToListAsync());
        }

        // GET: AidTypes/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aidType = await _context.AidTypes
                .FirstOrDefaultAsync(m => m.AidTypeID == id);
            if (aidType == null)
            {
                return NotFound();
            }

            return View(aidType);
        }

        // GET: AidTypes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: AidTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AidTypeID,Name")] AidType aidType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aidType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aidType);
        }

        // GET: AidTypes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aidType = await _context.AidTypes.FindAsync(id);
            if (aidType == null)
            {
                return NotFound();
            }
            return View(aidType);
        }

        // POST: AidTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AidTypeID,Name")] AidType aidType)
        {
            if (id != aidType.AidTypeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aidType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AidTypeExists(aidType.AidTypeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aidType);
        }

        // GET: AidTypes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aidType = await _context.AidTypes
                .FirstOrDefaultAsync(m => m.AidTypeID == id);
            if (aidType == null)
            {
                return NotFound();
            }

            return View(aidType);
        }

        // POST: AidTypes/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aidType = await _context.AidTypes.FindAsync(id);
            _context.AidTypes.Remove(aidType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AidTypeExists(int id)
        {
            return _context.AidTypes.Any(e => e.AidTypeID == id);
        }
    }
}

Disaster Alleviation Web/Controllers/DisastersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Disaster_Alleviation_Web.Data;
using Disaster_Alleviation_Web.Models;
using Microsoft.AspNetCore.Authorization;

namespace Disaster_Alleviation_Web.Controllers
{
    public class DisastersController : Controller
    {
        private readonly DisasterReliefContext _context;

        public DisastersController(DisasterReliefContext context)
        {
            _context = context;
        }

        // GET: Disasters
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var disasterReliefContext = _context.Disasters.Include(d => d.AidType);
            return View(await disasterReliefContext.ToListAsync());
        }

        // GET: Disasters/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disaster = await _context.Disasters
                .Include(d => d.AidType)
                .FirstOrDefaultAsync(m => m.DisasterID == id);
            if (disaster == null)
            {
                return NotFound();
            }

            return View(disaster);
        }

        // GET: Disasters/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["AidTypeID"] = new SelectList(_context.AidTypes, "AidTypeID", "Name");
            return View();
        }

        // POST: Disasters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DisasterID,StartDate,EndDate,Description,Location,AidTypeID")] Disaster disaster)
        {
            if (ModelState.IsValid)
            {
                _context.Add(disaster);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AidTypeID"] = new SelectList(_context.AidTypes, "AidTypeID", "Name", disaster.AidTypeID);
            return View(disaster);
        }

        // GET: Disasters/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disaster = await _context.Disasters.FindAsync(id);
            if (disaster == null)
            {
                return NotFound();
            }
            ViewData["AidTypeID"] = new SelectList(_context.AidTypes, "AidTypeID", "Name", disaster.AidTypeID);
            return View(disaster);
        }

        // POST: Disasters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DisasterID,StartDate,EndDate,Description,Location,AidTypeID")] Disaster disaster)
        {
            if (id != disaster.DisasterID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(disaster);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DisasterExists(disaster.DisasterID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AidTypeID"] = new SelectList(_context.AidTypes, "AidTypeID", "Name", disaster.AidTypeID);
            return View(disaster);
        }

        // GET: Disasters/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disaster = await _context.Disasters
                .Include(d => d.AidType)
                .FirstOrDefaultAsync(m => m.DisasterID == id);
            if (disaster == null)
            {
                return NotFound();
            }

            return View(disaster);
        }

        // POST: Disasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var disaster = await _context.Disasters.FindAsync(id);
            _context.Disasters.Remove(disaster);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DisasterExists(int id)
        {
            return _context.Disasters.Any(e => e.DisasterID == id);
        }
    }
}

Disaster Alleviation Web/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Disaster_Alleviation_Web.Data;
using Disaster_Alleviation_Web.Models.Donation;
using Microsoft.AspNetCore.Authorization;

namespace Disaster_Alleviation_Web.Controllers
{
    public class GoodsController : Controller
    {
        private readonly DisasterReliefContext _context;

        public GoodsController(DisasterReliefContext context)
        {
            _context = context;
        }


        // GET: Goods
        [Authorize]
        public async Task<IActionResult> Index()
        {

            var goods = _context.Goods.
                Include(g => g.Category)
                .Include(g => g.Disaster)
                .AsNoTracking();
            return View(await goods.ToListAsync());
        }

        // GET: Goods/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var good = await _context.Goods
                .Include(g => g.Category)
                .Include(g => g.Disaster)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.GoodID == id);
            if (good == null)
            {
                return NotFound();
            }

            return View(good);
        }

        // GET: Goods/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "Name");
            ViewData["DisasterID"] = new SelectList(_context.Disasters, "DisasterID", "DisasterID");
            return View();
        }

        // POST: Goods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GoodID,DonationDate,NumberOfItems,Description,DonorName,CategoryID,DisasterID")] Good good)
        {
            if (ModelState.IsValid)
            {
                _context.Add(good);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "Name", good.CategoryID);
            ViewData["DisasterID"] = new SelectList(_context.Disasters, "DisasterID", "DisasterID", good.DisasterID);
            return View(good);
        }

        // GET: Goods/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var good = await _context.Goods.FindAsync(id);
            if (good == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "Name", good.CategoryID);
            ViewData["DisasterID"] = new SelectList(_context.Disasters, "DisasterID", "DisasterID", good.DisasterID);
            return View(good);
        }

        // POST: Goods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GoodID,DonationDate,NumberOfItems,Description,DonorName,CategoryID,DisasterID")] Good good)
        {
            if (id != good.GoodID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(good);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GoodExists(good.GoodID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryID", good.CategoryID);
            ViewData["DisasterID"] = new SelectList(_context.Disasters, "DisasterID", "DisasterID", good.DisasterID);
            return View(good);
        }

        // GET: Goods/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var good = await _context.Goods
                .Include(g => g.Category)
                .Include(g => g.Disaster)
                .FirstOrDefaultAsync(m => m.GoodID == id);
            if (good == null)
            {
                return NotFound();
            }

            return View(good);
        }

        // POST: Goods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var good = await _context.Goods.FindAsync(id);
            _context.Goods.Remove(good);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GoodExists(int id)
        {
            return _context.Goods.Any(e => e.GoodID == id);
        }
    }
}

Disaster Alleviation Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Disaster Relief </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3"  style="background-color: #ba68c8">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Disaster Relief</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Stats
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="MonetaryStats">Monetary Stat</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="GoodsStats">Goods Stat</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="DisasterStats">Disaster Stat</a>
                                </li>
                            </ul>
                        </li>

                         <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> 
                                Donation
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Monetaries" asp-action="Index">Monetary</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Goods" asp-action="Index">Goods</a>
                                </li>
                            </ul>                 
                        </li>

                        
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Disasters" asp-action="Index">Disaster</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="AidTypes" asp-action="Index">Aid Type</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="GoodsPurchases" asp-action="Index">Goods Purchases</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Disaster Relief - ST10118615
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>